spring.application.name=webshop

spring.datasource.url=jdbc:mysql://localhost:3306/webshop
spring.datasource.username=root
spring.datasource.password=Sonyericsson94@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false